bright_smile/administration/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .baseviews import (    
    SpecialityViewSet
)
from .views.clinic_views import ClinicListView, ClinicDetailView, ClinicCreateView, ClinicUpdateView, ClinicDeleteView,manage_affiliations, remove_affiliation,ClinicViewSet, get_clinics
from .views.doctor_views import DoctorListView, DoctorDetailView, DoctorCreateView, DoctorUpdateView, DoctorDeleteView,DoctorViewSet
from .views.patient_views import PatientListView, PatientDetailView, PatientCreateView, PatientUpdateView, PatientDeleteView, PatientViewSet
from .views.visit_views import add_visit,get_doctors, get_specialties,delete_visit
from .views.appointment_views import schedule_appointment, get_doctors_with_clinic_and_procedure, get_available_slots, delete_appointment, get_doctor_schedule

from django.contrib.auth import views as auth_views

router = DefaultRouter()
router.register(r'api/clinics', ClinicViewSet, basename='clinic')
router.register(r'api/doctors', DoctorViewSet, basename='doctor')
router.register(r'api/patients', PatientViewSet, basename='patient')
router.register(r'api/specialties', SpecialityViewSet, basename='specialty')

urlpatterns = [

    # Authentication URLs
    path('login/', auth_views.LoginView.as_view(template_name='administration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Clinic URLs
    path('clinics/', ClinicListView.as_view(), name='clinic_list'),
    path('clinics/create/', ClinicCreateView.as_view(), name='clinic_create'),
    path('clinics/<int:pk>/', ClinicDetailView.as_view(), name='clinic_detail'),
    path('clinics/<int:pk>/update/', ClinicUpdateView.as_view(), name='clinic_update'),
    path('clinics/<int:pk>/delete/', ClinicDeleteView.as_view(), name='clinic_delete'),

    path('clinics/<int:pk>/', ClinicDetailView.as_view(), name='clinic_detail'),
    path('clinics/<int:pk>/edit/', ClinicUpdateView.as_view(), name='clinic_update'),
    path('clinics/<int:clinic_id>/affiliations/', manage_affiliations, name='manage_affiliations'),
    path('clinics/<int:clinic_id>/affiliations/<int:affiliation_id>/', manage_affiliations, name='edit_affiliation'),

    path('affiliations/remove/<int:affiliation_id>/', remove_affiliation, name='remove_affiliation'),

    # Doctor URLs
    path('doctors/', DoctorListView.as_view(), name='doctor_list'),
    path('doctors/create/', DoctorCreateView.as_view(), name='doctor_create'),
    path('doctors/<int:pk>/', DoctorDetailView.as_view(), name='doctor_detail'),
    path('doctors/<int:pk>/update/', DoctorUpdateView.as_view(), name='doctor_update'),
    path('doctors/<int:pk>/delete/', DoctorDeleteView.as_view(), name='doctor_delete'),

    # Patient URLs
    path('patients/', PatientListView.as_view(), name='patient_list'),
    path('patients/create/', PatientCreateView.as_view(), name='patient_create'),
    path('patients/<int:pk>/', PatientDetailView.as_view(), name='patient_detail'),
    path('patients/<int:pk>/update/', PatientUpdateView.as_view(), name='patient_update'),
    path('patients/<int:pk>/delete/', PatientDeleteView.as_view(), name='patient_delete'),

    path('patients/<int:patient_id>/visit/add/', add_visit, name='add_visit'),
    path('patients/<int:patient_id>/appointment/schedule/', schedule_appointment, name='schedule_appointment'),

    path('api/get-doctors/', get_doctors, name='get_doctors'),
    path('api/get-specialties/', get_specialties, name='get_specialties'),
    path('api/get-clinics/', get_clinics, name='get_clinics'),
    path('api/get-doctors-with-clinic-and-procedure/', get_doctors_with_clinic_and_procedure, name='get_doctors_with_clinic_and_procedure'),
    path('api/get-available-slots/', get_available_slots, name='get_available_slots'),
    path('api/get-doctor-schedule/', get_doctor_schedule, name='get_doctor_schedule'),

    path('appointments/delete/<int:appointment_id>/', delete_appointment, name='delete_appointment'),
    path('visit/delete/<int:visit_id>/', delete_visit, name='delete_visit'),

    path('', include(router.urls)),

]

bright_smile/bright_smile/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', include('administration.urls')),
]

bright_smile/administration/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone

# Clinic and Doctor-related models
class Clinic(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=15)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Specialty(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Doctor(models.Model):
    NPI = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone_number = models.CharField(max_length=15)
    specialties = models.ManyToManyField(Specialty, related_name='doctors')
    # clinics = models.ManyToManyField(Clinic, related_name='doctors')


    def __str__(self):
        return self.name

DAYS_OF_WEEK = [
    ('Mon', 'Monday'),
    ('Tue', 'Tuesday'),
    ('Wed', 'Wednesday'),
    ('Thu', 'Thursday'),
    ('Fri', 'Friday'),
    ('Sat', 'Saturday'),
    ('Sun', 'Sunday'),
]

class DoctorClinicAffiliation(models.Model):
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    clinic = models.ForeignKey(Clinic, on_delete=models.CASCADE)
    office_address = models.TextField()

    def __str__(self):
        return f'{self.doctor.name} at {self.clinic.name}'
    
    def get_working_days_display(self):
        return ', '.join(self.working_days.split(','))

Doctor.clinics = models.ManyToManyField(Clinic, through=DoctorClinicAffiliation, related_name='affiliated_doctors')

class DoctorSchedule(models.Model):
    affiliation = models.ForeignKey(DoctorClinicAffiliation, on_delete=models.CASCADE, related_name='schedules')
    day_of_week = models.CharField(max_length=3, choices=DAYS_OF_WEEK)
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return f'{self.get_day_of_week_display()} ({self.start_time} - {self.end_time})'
    
    def clean(self):
        """
        Ensure that the end time is greater than the start time.
        """
        if self.start_time and self.end_time and self.start_time >= self.end_time:
            raise ValidationError('End time must be after start time.')

# Patient-related models
class Patient(models.Model):
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    last_4_ssn = models.CharField(max_length=4)
    phone_number = models.CharField(max_length=15)
    gender = models.CharField(max_length=10)
    address = models.TextField()

    def __str__(self):
        return self.name

class Procedure(models.Model):
    name = models.CharField(max_length=100)  # e.g., Cleaning, Root Canal

    def __str__(self):
        return self.name

class Visit(models.Model):
    patient = models.ForeignKey(Patient, related_name='visits', on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, related_name='visits', on_delete=models.CASCADE)
    clinic = models.ForeignKey(Clinic, related_name='visits', on_delete=models.CASCADE)
    date_time = models.DateTimeField()  # Date and Time of the visit
    procedures_done = models.ManyToManyField(Specialty)  # Procedures done during the visit
    doctor_notes = models.TextField(blank=True)  # Notes from the doctor

    def __str__(self):
        return f'Visit on {self.date_time} by {self.doctor}'

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, related_name='appointments', on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, related_name='appointments', on_delete=models.CASCADE)
    clinic = models.ForeignKey(Clinic, related_name='appointments', on_delete=models.CASCADE)
    procedure = models.ForeignKey(Specialty, related_name='appointments', on_delete=models.CASCADE)
    date_time = models.DateTimeField()  # Date and Time of the appointment
    date_booked = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'Appointment on {self.date_time} with {self.doctor}'

bright_smile/administration/views/appointment_views.py
from datetime import datetime, timedelta

from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AppointmentForm
from ..models import Doctor, Patient, DoctorClinicAffiliation, DoctorSchedule, Appointment


def schedule_appointment(request, patient_id):
    patient = get_object_or_404(Patient, id=patient_id)

    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        print(form.errors)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.patient = patient
            appointment.save()
            return redirect('patient_detail', pk=patient_id)
    else:
        form = AppointmentForm()

    return render(request, 'administration/schedule_appointment.html', {'form': form, 'patient': patient})


def get_doctors_with_clinic_and_procedure(request):
    clinic_id = request.GET.get('clinic_id')
    procedure_id = request.GET.get('procedure_id')

    # Get doctors affiliated with the selected clinic who offer the selected procedure
    doctors = Doctor.objects.filter(
        doctorclinicaffiliation__clinic=clinic_id,
        specialties=procedure_id
    ).distinct()

    doctor_list = list(doctors.values('id', 'name'))
    return JsonResponse(doctor_list, safe=False)

def get_available_slots(request):
    doctor_id = request.GET.get('doctor_id')
    clinic_id = request.GET.get('clinic_id')
    appointment_date = request.GET.get('date')  # Expected format: YYYY-MM-DD

    # Convert the appointment_date to a datetime object and get the day of the week
    appointment_date_obj = timezone.make_aware(datetime.strptime(appointment_date, '%Y-%m-%d'))
    day_of_week = appointment_date_obj.strftime('%a')

    # Fetch the doctor's schedule for the specific clinic and day
    affiliation = DoctorClinicAffiliation.objects.get(doctor_id=doctor_id, clinic_id=clinic_id)
    schedule = DoctorSchedule.objects.filter(affiliation=affiliation, day_of_week=day_of_week).first()

    if not schedule:
        return JsonResponse({"error": "Doctor is not available on the selected day"}, status=400)

    # Fetch existing appointments for the doctor at this clinic on the selected date
    existing_appointments = Appointment.objects.filter(
        doctor_id=doctor_id,
        clinic_id=clinic_id,
        date_time__date=appointment_date_obj.date()
    )

    appointment_duration = timedelta(minutes=15)

    # Initialize available slots based on doctor's working hours
    start_time = timezone.make_aware(datetime.combine(appointment_date_obj.date(), schedule.start_time))
    end_time = timezone.make_aware(datetime.combine(appointment_date_obj.date(), schedule.end_time))

    available_slots = []
    current_time = start_time

    booked_ranges = [
        (appointment.date_time, appointment.date_time + appointment_duration)
        for appointment in existing_appointments
    ]

    while current_time + appointment_duration <= end_time:
        is_conflict = False
        for start, end in booked_ranges:
            if start <= current_time < end:
                is_conflict = True
                break

        if not is_conflict:
            available_slots.append(current_time.strftime('%Y-%m-%d %H:%M:%S'))

        current_time += appointment_duration

    if not available_slots:
        return JsonResponse({"error": "No available slots for the selected day"}, status=400)

    return JsonResponse(available_slots, safe=False)


def delete_appointment(request, appointment_id):
    appointment = get_object_or_404(Appointment, pk=appointment_id)
    patient_id = appointment.patient.pk
    appointment.delete()
    return redirect('patient_detail', pk=patient_id)



def get_doctor_schedule(request):
    doctor_id = request.GET.get('doctor_id')
    clinic_id = request.GET.get('clinic_id')

    # Get the doctor's affiliation with the clinic
    affiliation = DoctorClinicAffiliation.objects.get(doctor_id=doctor_id, clinic_id=clinic_id)

    # Fetch the doctor's schedule for that clinic
    schedules = DoctorSchedule.objects.filter(affiliation=affiliation).values('day_of_week', 'start_time', 'end_time')

    schedule_list = list(schedules)
    return JsonResponse(schedule_list, safe=False)

bright_smile/administration/views/doctor_views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from rest_framework import viewsets

from ..forms import DoctorForm
from ..models import Doctor, Patient, DoctorClinicAffiliation, Visit, Appointment
from ..serializers import DoctorSerializer


# REST API ViewSets
class DoctorViewSet(viewsets.ModelViewSet):
    queryset = Doctor.objects.none()
    serializer_class = DoctorSerializer



# Doctor CRUD
class DoctorListView(LoginRequiredMixin, ListView):
    model = Doctor
    template_name = 'administration/doctor/doctor_list.html'
    context_object_name = 'doctors'

    def get_queryset(self):
        doctors = Doctor.objects.prefetch_related('specialties', 'doctorclinicaffiliation_set').all()

        for doctor in doctors:
            # Fetch patients who visited this doctor
            past_visits = Visit.objects.filter(doctor=doctor).values_list('patient', flat=True)

            # Fetch patients who have future appointments with this doctor
            future_appointments = Appointment.objects.filter(doctor=doctor, date_time__gte=datetime.now()).values_list('patient', flat=True)

            # Combine and remove duplicates
            unique_patients = set(list(past_visits) + list(future_appointments))

            # Store the number of unique patients in the doctor object
            doctor.unique_patient_count = len(unique_patients)

        return doctors

class DoctorDetailView(LoginRequiredMixin, DetailView):
    model = Doctor
    template_name = 'administration/doctor/doctor_detail.html'
    context_object_name = 'doctor'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Fetch affiliations with clinics
        affiliations = DoctorClinicAffiliation.objects.filter(doctor=self.object).prefetch_related('schedules')
        context['affiliations'] = affiliations

        # Get the unique list of patients affiliated with the doctor (from visits or appointments)
        patients_from_visits = Patient.objects.filter(visits__doctor=self.object).distinct()
        patients_from_appointments = Patient.objects.filter(appointments__doctor=self.object).distinct()

        # Combine the two querysets and remove duplicates manually in Python
        all_patients = list(patients_from_visits) + list(patients_from_appointments)
        # Convert to a set of unique patient IDs to remove duplicates
        unique_patients = {patient.id: patient for patient in all_patients}.values()

        # Pass the unique patients to the context
        context['affiliated_patients'] = unique_patients
        
        return context

class DoctorCreateView(LoginRequiredMixin, CreateView):
    model = Doctor
    form_class = DoctorForm
    template_name = 'administration/doctor/doctor_form.html'
    success_url = reverse_lazy('doctor_list')

class DoctorUpdateView(LoginRequiredMixin, UpdateView):
    model = Doctor
    form_class = DoctorForm
    template_name = 'administration/doctor/doctor_form.html'
    success_url = reverse_lazy('doctor_list')

class DoctorDeleteView(LoginRequiredMixin, DeleteView):
    model = Doctor
    template_name = 'administration/doctor/doctor_confirm_delete.html'
    success_url = reverse_lazy('doctor_list')

bright_smile/administration/views/visit_views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

from ..forms import VisitForm
from ..models import Doctor, Patient, DoctorClinicAffiliation, Visit


def add_visit(request, patient_id):
    patient = get_object_or_404(Patient, pk=patient_id)

    if request.method == 'POST':
        form = VisitForm(request.POST)
        if form.is_valid():
            visit = form.save(commit=False)
            visit.patient = patient
            visit.save()
            form.save_m2m()  # Save Many-to-Many fields (procedures_done)
            return redirect('patient_detail', pk=patient.pk)
    else:
        form = VisitForm()

    return render(request, 'administration/add_visit.html', {'form': form, 'patient': patient})


def get_doctors(request):
    clinic_id = request.GET.get('clinic_id')
    doctors = DoctorClinicAffiliation.objects.filter(clinic_id=clinic_id).select_related('doctor').values('doctor__id', 'doctor__name')
    return JsonResponse(list(doctors), safe=False)

def get_specialties(request):
    doctor_id = request.GET.get('doctor_id')
    specialties = Doctor.objects.get(pk=doctor_id).specialties.values('id', 'name')
    return JsonResponse(list(specialties), safe=False)


def delete_visit(request, visit_id):
    visit = get_object_or_404(Visit, pk=visit_id)
    patient_id = visit.patient.pk  # Save the patient's ID to redirect back after deletion
    visit.delete()
    return redirect('patient_detail', pk=patient_id)

bright_smile/administration/templates/administration/add_visit.html
{% extends "administration/base.html" %}

{% block content %}
<h2 class="mb-4">Add Visit for {{ patient.name }}</h2>

<form method="post" class="needs-validation" novalidate>
    {% csrf_token %}
    
    <div class="mb-3">
        {{ form.clinic.label_tag }} {{ form.clinic }}
    </div>

    <div id="doctor-container" class="mb-3" style="display: none;">
        <label for="id_doctor">{{ form.doctor.label }}</label>
        {{ form.doctor }}
    </div>

    <div id="no-doctors-warning" style="display: none; color: red;">
        No doctors affiliated with this clinic.
    </div>

    <div id="procedures-container" class="mb-3" style="display: none;">
        <label for="id_procedures_done">Procedures Done:</label>
        <div id="id_procedures_done"></div>
    </div>

    <div id="no-specialties-warning" style="display: none; color: red;">
        No specialties available for the selected doctor.
    </div>

    <!-- Hidden date, time, and doctor notes fields -->
    <div id="visit-details-container" class="mb-3" style="display: none;">
        <div class="mb-3">
            <label for="id_date_time">{{ form.date_time.label }}</label>
            {{ form.date_time }} 
        </div>
        
        <div class="mb-3">
            <label for="id_doctor_notes">{{ form.doctor_notes.label }}</label>
            {{ form.doctor_notes }}
        </div>
    </div>

    <div class="mb-3">
        <button type="submit" class="btn btn-primary" id="submit-button" disabled>Save Visit</button>
        <a href="{% url 'patient_detail' patient.pk %}" class="btn btn-secondary">Cancel</a>
    </div>
</form>

<script>
    const doctorContainer = document.getElementById('doctor-container');
    const proceduresContainer = document.getElementById('procedures-container');
    const visitDetailsContainer = document.getElementById('visit-details-container');
    const submitButton = document.getElementById('submit-button');
    const noDoctorsWarning = document.getElementById('no-doctors-warning');
    const noSpecialtiesWarning = document.getElementById('no-specialties-warning');


    doctorContainer.style.display = 'none';
    proceduresContainer.style.display = 'none';
    visitDetailsContainer.style.display = 'none';
    submitButton.disabled = true;

    document.getElementById('id_clinic').addEventListener('change', function () {
        const clinicId = this.value;
        

        doctorContainer.style.display = 'none';
        proceduresContainer.style.display = 'none';
        visitDetailsContainer.style.display = 'none';
        submitButton.disabled = true;
        noDoctorsWarning.style.display = 'none';
        noSpecialtiesWarning.style.display = 'none';

        fetch(`/administration/api/get-doctors/?clinic_id=${clinicId}`)
            .then(response => response.json())
            .then(data => {
                const doctorSelect = document.getElementById('id_doctor');
                doctorSelect.innerHTML = '';  // Clear previous options

                if (data.length > 0) {

                    doctorContainer.style.display = 'block';
                    data.forEach(doctor => {
                        const option = new Option(doctor.doctor__name, doctor.doctor__id);
                        doctorSelect.add(option);
                    });

                    const event = new Event('change');
                    doctorSelect.dispatchEvent(event);
                } else {

                    noDoctorsWarning.style.display = 'block';
                }
            })
            .catch(() => {
                noDoctorsWarning.style.display = 'block';
            });
    });

    document.getElementById('id_doctor').addEventListener('change', function () {
        const doctorId = this.value;
        

        proceduresContainer.style.display = 'none';
        visitDetailsContainer.style.display = 'none';
        submitButton.disabled = true;
        noSpecialtiesWarning.style.display = 'none';

        fetch(`/administration/api/get-specialties/?doctor_id=${doctorId}`)
            .then(response => response.json())
            .then(data => {
                const specialtiesContainer = document.getElementById('id_procedures_done');
                specialtiesContainer.innerHTML = '';

                if (data.length > 0) {
                    proceduresContainer.style.display = 'block';
                    data.forEach(specialty => {
                        const checkbox = document.createElement('input');
                        checkbox.type = 'checkbox';
                        checkbox.name = 'procedures_done';
                        checkbox.value = specialty.id;
                        checkbox.id = `specialty_${specialty.id}`;

                        const label = document.createElement('label');
                        label.htmlFor = checkbox.id;
                        label.textContent = specialty.name;
                        specialtiesContainer.appendChild(checkbox);
                        specialtiesContainer.appendChild(label);
                        specialtiesContainer.appendChild(document.createElement('br'));
                    });


                    visitDetailsContainer.style.display = 'block';

                    submitButton.disabled = false;
                } else {
                    noSpecialtiesWarning.style.display = 'block';
                }
            })
            .catch(() => {
                noSpecialtiesWarning.style.display = 'block';
            });
    });
</script>

{% endblock %}

bright_smile/administration/templates/administration/schedule_appointment.html
{% extends "administration/base.html" %}

{% block content %}
<h2>Schedule Appointment for {{ patient.name }}</h2>

<form method="post">
    {% csrf_token %}
    
    {{ form.procedure.label_tag }} {{ form.procedure }}

    <div id="clinic-container" style="display: none;">
        <br>
        {{ form.clinic.label_tag }} {{ form.clinic }}
        <span id="no-clinics-message" style="color: red; display: none;">No clinics available for the selected procedure.</span>
    </div>

    <div id="doctor-container" style="display: none;">
        <br>
        {{ form.doctor.label_tag }} {{ form.doctor }}
        <span id="no-doctors-message" style="color: red; display: none;">No doctors available for the selected clinic and procedure.</span>
    </div>

    <div id="schedule-container" style="display: none;">
        <br>
        <h4>Doctor's Schedule</h4>
        <div id="doctor-schedule"></div>
    </div>

    <div id="date-container" style="display: none;">
        <br>
        <label for="id_date">Select Appointment Date:</label>
        <input type="date" id="id_date" name="date">
    </div>

    <div id="slot-container" style="display: none;">
        <br>
        <label for="id_date_time">Available Time Slots:</label>
        <select id="id_date_time" name="date_time"></select>
        
    </div>
    <span id="no-slots-message" style="color: red; display: none;">No available time slots for the selected doctor on this date.</span>

    <br>
    <button type="submit" class="btn btn-primary" id="submit-button" disabled>Save Appointment</button>
</form>

<script>
    const clinicContainer = document.getElementById('clinic-container');
    const doctorContainer = document.getElementById('doctor-container');
    const scheduleContainer = document.getElementById('schedule-container');  // New
    const dateContainer = document.getElementById('date-container');
    const slotContainer = document.getElementById('slot-container');
    const submitButton = document.getElementById('submit-button');
    const noClinicsMessage = document.getElementById('no-clinics-message');
    const noDoctorsMessage = document.getElementById('no-doctors-message');
    const noSlotsMessage = document.getElementById('no-slots-message');

    document.getElementById('id_procedure').addEventListener('change', function () {
        const procedureId = this.value;
        
        clinicContainer.style.display = 'none';
        doctorContainer.style.display = 'none';
        scheduleContainer.style.display = 'none';
        dateContainer.style.display = 'none';
        slotContainer.style.display = 'none';
        submitButton.disabled = true;
        noClinicsMessage.style.display = 'none';

        fetch(`/administration/api/get-clinics/?procedure_id=${procedureId}`)
            .then(response => response.json())
            .then(data => {
                const clinicSelect = document.getElementById('id_clinic');
                clinicSelect.innerHTML = '';
                
                if (data.length > 0) {
                    clinicContainer.style.display = 'block';
                    data.forEach(clinic => {
                        const option = new Option(clinic.name, clinic.id);
                        clinicSelect.add(option);
                    });

                    clinicSelect.dispatchEvent(new Event('change'));
                } else {
                    noClinicsMessage.style.display = 'block';
                }
            })
            .catch(() => {
                noClinicsMessage.style.display = 'block';
            });
    });

    document.getElementById('id_clinic').addEventListener('change', function () {
        const clinicId = this.value;
        const procedureId = document.getElementById('id_procedure').value;

        doctorContainer.style.display = 'none';
        scheduleContainer.style.display = 'none';
        dateContainer.style.display = 'none';
        slotContainer.style.display = 'none';
        submitButton.disabled = true;
        noDoctorsMessage.style.display = 'none';

        fetch(`/administration/api/get-doctors-with-clinic-and-procedure/?clinic_id=${clinicId}&procedure_id=${procedureId}`)
            .then(response => response.json())
            .then(data => {
                const doctorSelect = document.getElementById('id_doctor');
                doctorSelect.innerHTML = '';
                
                if (data.length > 0) {
                    doctorContainer.style.display = 'block';
                    data.forEach(doctor => {
                        const option = new Option(doctor.name, doctor.id);
                        doctorSelect.add(option);
                    });
                    doctorSelect.dispatchEvent(new Event('change'));

                    dateContainer.style.display = 'block';
                } else {
                    noDoctorsMessage.style.display = 'block';
                }
            })
            .catch(() => {
                noDoctorsMessage.style.display = 'block';
            });
    });

    document.getElementById('id_doctor').addEventListener('change', function () {
        const doctorId = this.value;
        const clinicId = document.getElementById('id_clinic').value;

        fetch(`/administration/api/get-doctor-schedule/?doctor_id=${doctorId}&clinic_id=${clinicId}`)
            .then(response => response.json())
            .then(data => {
                const scheduleContainerContent = document.getElementById('doctor-schedule');
                scheduleContainerContent.innerHTML = '';
                
                if (data.length > 0) {
                    let scheduleHtml = '<ul>';
                    data.forEach(schedule => {
                        scheduleHtml += `<li>${schedule.day_of_week}: ${schedule.start_time} - ${schedule.end_time}</li>`;
                    });
                    scheduleHtml += '</ul>';
                    scheduleContainerContent.innerHTML = scheduleHtml;
                    scheduleContainer.style.display = 'block';
                } else {
                    scheduleContainerContent.innerHTML = '<p>No schedule available for the selected doctor at this clinic.</p>';
                }
            })
            .catch(() => {
                const scheduleContainerContent = document.getElementById('doctor-schedule');
                scheduleContainerContent.innerHTML = '<p>Error fetching schedule.</p>';
            });
    });

    document.getElementById('id_date').addEventListener('change', function () {
        const doctorId = document.getElementById('id_doctor').value;
        const clinicId = document.getElementById('id_clinic').value;
        const appointmentDate = this.value;

        // Reset slot field
        slotContainer.style.display = 'none';
        submitButton.disabled = true;
        noSlotsMessage.style.display = 'none';

        fetch(`/administration/api/get-available-slots/?doctor_id=${doctorId}&clinic_id=${clinicId}&date=${appointmentDate}`)
            .then(response => response.json())
            .then(data => {
                const slotSelect = document.getElementById('id_date_time');
                slotSelect.innerHTML = '';
                
                if (data.length > 0) {
                    slotContainer.style.display = 'block';
                    data.forEach(slot => {
                        const option = new Option(slot, slot);
                        slotSelect.add(option);
                    });
                    submitButton.disabled = false;
                } else {
                    noSlotsMessage.style.display = 'block';
                }
            })
            .catch(() => {
                noSlotsMessage.style.display = 'block';
            });
    });

    // Trigger slot loading when date is selected
    document.getElementById('id_date').addEventListener('change', function () {
        const doctorSelect = document.getElementById('id_doctor');
        doctorSelect.dispatchEvent(new Event('change'));
    });
</script>
{% endblock %}